CREATE TABLE types (nom VARCHAR(20) PRIMARY KEY, image VARCHAR(255));
CREATE TABLE pokemons ( pokedex_id INT PRIMARY KEY, nom VARCHAR(255), pv INT, attaque INT, defense INT, attaque_speciale INT, defense_speciale INT, vitesse INT, taille FLOAT, poids FLOAT);
CREATE TABLE pokemon_types ( pokedex_id INT, type VARCHAR(255), PRIMARY KEY (pokedex_id, type), FOREIGN KEY (pokedex_id) REFERENCES pokemons(pokedex_id), FOREIGN KEY (type) REFERENCES types(nom));
CREATE TABLE evolutions (pokedex_id INT, type VARCHAR(255), evolution_id INT, condition VARCHAR(255), PRIMARY KEY (pokedex_id, type), FOREIGN KEY (pokedex_id) REFERENCES pokemons(pokedex_id));
CREATE TABLE dresseur (id INT PRIMARY KEY, prenom VARCHAR(255), date_naissance DATE, console VARCHAR(50), date_inscription DATE);
CREATE TABLE pokemon_stocke_dans_pc (id INT PRIMARY KEY, id_pokemon INT, id_dresseur INT, surnom VARCHAR(255), niveau INT, date_stockage DATE, FOREIGN KEY (id_dresseur) REFERENCES dresseur(id), FOREIGN KEY (id_pokemon) REFERENCES pokemons(pokedex_id));
CREATE TABLE pokemon_stocke_dans_equipe (id INT PRIMARY KEY, id_pokemon INT, id_dresseur INT, surnom VARCHAR(50), niveau INT, pv_restant INT, position INT, FOREIGN KEY (id_dresseur) REFERENCES dresseur(id), FOREIGN KEY (id_pokemon) REFERENCES pokemons(pokedex_id));
CREATE TABLE arenes (id INT PRIMARY KEY, nom VARCHAR(50), nom_champion VARCHAR(50), badge VARCHAR(50), date_creation DATE);
CREATE TABLE combats_arenes (id INT PRIMARY KEY, id_arene INT, id_dresseur INT, date_combat DATE, resultat VARCHAR(50), FOREIGN KEY (id_arene) REFERENCES arenes(id), FOREIGN KEY (id_dresseur) REFERENCES dresseur(id));
CREATE TABLE combats (id INT PRIMARY KEY, id_dresseur1 INT, id_dresseur2 INT, date_combat DATE, resultat VARCHAR(50), FOREIGN KEY (id_dresseur1) REFERENCES dresseur(id), FOREIGN KEY (id_dresseur2) REFERENCES dresseur(id));
CREATE TABLE categories_objets (nom VARCHAR(50) PRIMARY KEY, image VARCHAR(50));
CREATE TABLE objets (id INT PRIMARY KEY, nom VARCHAR(50), categorie VARCHAR(50), prix INT, FOREIGN KEY (categorie) REFERENCES categories_objets(nom));
CREATE TABLE objets_dresseurs (id INT PRIMARY KEY, id_objet INT, id_dresseur INT, quantite INT, FOREIGN KEY (id_objet) REFERENCES objets(id), FOREIGN KEY (id_dresseur) REFERENCES dresseur(id));
CREATE TABLE transactions (id INT PRIMARY KEY, id_dresseur INT, date DATE, montant INT, type VARCHAR(50), objet VARCHAR(50), FOREIGN KEY (id_dresseur) REFERENCES dresseur(id));
